# Welcome to Jekyll!
#

# Site settings
title: AMJAD KHAN
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: AMJAD KHAN # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amjadajmer.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/amjadajmer
  facebook-official: https://facebook.com/amjadajmer
  github: https://github.com/amjadajmer
  youtube-square: https://www.youtube.com/
  slideshare: https://www.slideshare.net/
  linkedin-square: https://linkedin.com/in/amjadajmer
  cloud: https://developer.salesforce.com/forums/ForumsProfile?userId=005F0000006JZcNIAW
  #google-plus-square:
  #email: /contact/
  #flickr:
  #instagram:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
